CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE EXTENSION IF NOT EXISTS vector;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE genres (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(150) NOT NULL,
        "NormalizedName" character varying(150) NOT NULL,
        CONSTRAINT "PK_genres" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE keywords (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(150) NOT NULL,
        "NormalizedName" character varying(150) NOT NULL,
        CONSTRAINT "PK_keywords" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE people (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(300) NOT NULL,
        "NormalizedName" character varying(300) NOT NULL,
        CONSTRAINT "PK_people" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE sources (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(150) NOT NULL,
        "BaseUrl" character varying(2000) NOT NULL,
        "Enabled" boolean NOT NULL,
        "AdapterType" character varying(150) NOT NULL,
        "LastCrawlAt" timestamp with time zone,
        CONSTRAINT "PK_sources" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE crawl_jobs (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SourceId" integer NOT NULL,
        "StartedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        "Status" integer NOT NULL,
        "PagesVisited" integer NOT NULL,
        "MoviesFound" integer NOT NULL,
        "MoviesCreated" integer NOT NULL,
        "MoviesUpdated" integer NOT NULL,
        CONSTRAINT "PK_crawl_jobs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_crawl_jobs_sources_SourceId" FOREIGN KEY ("SourceId") REFERENCES sources ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE movies (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ExternalId" character varying(200) NOT NULL,
        "SourceId" integer NOT NULL,
        "Title" character varying(500) NOT NULL,
        "OriginalTitle" character varying(500),
        "Year" integer,
        "Overview" text,
        "Rating" double precision,
        "PosterUrl" text,
        "BackdropUrl" text,
        "PlatformUrl" character varying(2000) NOT NULL,
        "Language" character varying(50),
        "Country" character varying(100),
        "MetadataHash" character varying(64),
        "EmbeddingText" text,
        "Embedding" vector(384),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "LastSeenAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_movies" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_movies_sources_SourceId" FOREIGN KEY ("SourceId") REFERENCES sources ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE crawl_errors (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CrawlJobId" integer NOT NULL,
        "Url" character varying(2000) NOT NULL,
        "ErrorType" character varying(200) NOT NULL,
        "Message" character varying(4000) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_crawl_errors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_crawl_errors_crawl_jobs_CrawlJobId" FOREIGN KEY ("CrawlJobId") REFERENCES crawl_jobs ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE movie_cast (
        "MovieId" integer NOT NULL,
        "PersonId" integer NOT NULL,
        "Character" character varying(300),
        "BillingOrder" integer NOT NULL,
        CONSTRAINT "PK_movie_cast" PRIMARY KEY ("MovieId", "PersonId"),
        CONSTRAINT "FK_movie_cast_movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES movies ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_movie_cast_people_PersonId" FOREIGN KEY ("PersonId") REFERENCES people ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE movie_crew (
        "MovieId" integer NOT NULL,
        "PersonId" integer NOT NULL,
        "Role" character varying(50) NOT NULL,
        CONSTRAINT "PK_movie_crew" PRIMARY KEY ("MovieId", "PersonId", "Role"),
        CONSTRAINT "FK_movie_crew_movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES movies ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_movie_crew_people_PersonId" FOREIGN KEY ("PersonId") REFERENCES people ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE movie_directors (
        "MovieId" integer NOT NULL,
        "PersonId" integer NOT NULL,
        CONSTRAINT "PK_movie_directors" PRIMARY KEY ("MovieId", "PersonId"),
        CONSTRAINT "FK_movie_directors_movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES movies ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_movie_directors_people_PersonId" FOREIGN KEY ("PersonId") REFERENCES people ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE movie_genres (
        "MovieId" integer NOT NULL,
        "GenreId" integer NOT NULL,
        CONSTRAINT "PK_movie_genres" PRIMARY KEY ("MovieId", "GenreId"),
        CONSTRAINT "FK_movie_genres_genres_GenreId" FOREIGN KEY ("GenreId") REFERENCES genres ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_movie_genres_movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES movies ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE TABLE movie_keywords (
        "MovieId" integer NOT NULL,
        "KeywordId" integer NOT NULL,
        CONSTRAINT "PK_movie_keywords" PRIMARY KEY ("MovieId", "KeywordId"),
        CONSTRAINT "FK_movie_keywords_keywords_KeywordId" FOREIGN KEY ("KeywordId") REFERENCES keywords ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_movie_keywords_movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES movies ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_crawl_errors_CrawlJobId" ON crawl_errors ("CrawlJobId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_crawl_jobs_SourceId" ON crawl_jobs ("SourceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_crawl_jobs_StartedAt" ON crawl_jobs ("StartedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_crawl_jobs_Status" ON crawl_jobs ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_genres_NormalizedName" ON genres ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_keywords_NormalizedName" ON keywords ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_movie_cast_PersonId" ON movie_cast ("PersonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_movie_crew_PersonId" ON movie_crew ("PersonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_movie_directors_PersonId" ON movie_directors ("PersonId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_movie_genres_GenreId" ON movie_genres ("GenreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_movie_keywords_KeywordId" ON movie_keywords ("KeywordId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_movies_LastSeenAt" ON movies ("LastSeenAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_movies_Rating" ON movies ("Rating");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_movies_SourceId_ExternalId" ON movies ("SourceId", "ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_movies_Title" ON movies ("Title");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_movies_Year" ON movies ("Year");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE INDEX "IX_people_NormalizedName" ON people ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_sources_Name" ON sources ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912170243_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912170243_InitialCreate', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912172758_AddFullTextSearch') THEN
    CREATE EXTENSION IF NOT EXISTS unaccent;
    CREATE EXTENSION IF NOT EXISTS vector;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912172758_AddFullTextSearch') THEN
    ALTER TABLE movies ADD search_vector tsvector;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912172758_AddFullTextSearch') THEN
    CREATE INDEX ix_movies_search_vector ON movies USING GIN (search_vector);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912172758_AddFullTextSearch') THEN
    CREATE OR REPLACE FUNCTION refresh_movie_search_vector(p_movie_id integer) RETURNS void AS $$
    BEGIN
        UPDATE movies m
        SET search_vector =
            setweight(to_tsvector('simple', unaccent(coalesce(m."Title", ''))), 'A') ||
            setweight(to_tsvector('simple', unaccent(coalesce(m."OriginalTitle", ''))), 'A') ||
            setweight(to_tsvector('simple', unaccent(coalesce((
                SELECT string_agg(g."Name", ' ') FROM movie_genres mg
                JOIN genres g ON g."Id" = mg."GenreId" WHERE mg."MovieId" = m."Id"
            ), ''))), 'B') ||
            setweight(to_tsvector('simple', unaccent(coalesce((
                SELECT string_agg(p."Name", ' ') FROM movie_directors md
                JOIN people p ON p."Id" = md."PersonId" WHERE md."MovieId" = m."Id"
            ), ''))), 'B') ||
            setweight(to_tsvector('simple', unaccent(coalesce((
                SELECT string_agg(p."Name", ' ') FROM movie_cast mc
                JOIN people p ON p."Id" = mc."PersonId" WHERE mc."MovieId" = m."Id"
            ), ''))), 'C') ||
            setweight(to_tsvector('simple', unaccent(coalesce((
                SELECT string_agg(k."Name", ' ') FROM movie_keywords mk
                JOIN keywords k ON k."Id" = mk."KeywordId" WHERE mk."MovieId" = m."Id"
            ), ''))), 'C') ||
            setweight(to_tsvector('simple', unaccent(coalesce(m."Overview", ''))), 'D')
        WHERE m."Id" = p_movie_id;
    END;
    $$ LANGUAGE plpgsql;

    CREATE OR REPLACE FUNCTION trg_movies_search_vector() RETURNS trigger AS $$
    BEGIN
        PERFORM refresh_movie_search_vector(NEW."Id");
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER movies_search_vector_trigger
    AFTER INSERT OR UPDATE OF "Title", "OriginalTitle", "Overview" ON movies
    FOR EACH ROW EXECUTE FUNCTION trg_movies_search_vector();

    CREATE OR REPLACE FUNCTION trg_movie_relation_search_vector() RETURNS trigger AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            PERFORM refresh_movie_search_vector(OLD."MovieId");
            RETURN OLD;
        ELSE
            PERFORM refresh_movie_search_vector(NEW."MovieId");
            RETURN NEW;
        END IF;
    END;
    $$ LANGUAGE plpgsql;

    CREATE TRIGGER movie_genres_search_vector_trigger
    AFTER INSERT OR UPDATE OR DELETE ON movie_genres
    FOR EACH ROW EXECUTE FUNCTION trg_movie_relation_search_vector();

    CREATE TRIGGER movie_directors_search_vector_trigger
    AFTER INSERT OR UPDATE OR DELETE ON movie_directors
    FOR EACH ROW EXECUTE FUNCTION trg_movie_relation_search_vector();

    CREATE TRIGGER movie_cast_search_vector_trigger
    AFTER INSERT OR UPDATE OR DELETE ON movie_cast
    FOR EACH ROW EXECUTE FUNCTION trg_movie_relation_search_vector();

    CREATE TRIGGER movie_keywords_search_vector_trigger
    AFTER INSERT OR UPDATE OR DELETE ON movie_keywords
    FOR EACH ROW EXECUTE FUNCTION trg_movie_relation_search_vector();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912172758_AddFullTextSearch') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912172758_AddFullTextSearch', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912175719_AddNormalizedTitle') THEN
    ALTER TABLE movies ADD "NormalizedTitle" character varying(500) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912175719_AddNormalizedTitle') THEN
    UPDATE movies SET "NormalizedTitle" = lower("Title");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912175719_AddNormalizedTitle') THEN
    CREATE INDEX "IX_movies_NormalizedTitle_Year" ON movies ("NormalizedTitle", "Year");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912175719_AddNormalizedTitle') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912175719_AddNormalizedTitle', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912182156_AddEmbeddingHnswIndex') THEN
    CREATE INDEX ix_movies_embedding_hnsw ON movies USING hnsw ("Embedding" vector_cosine_ops);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912182156_AddEmbeddingHnswIndex') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912182156_AddEmbeddingHnswIndex', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912191746_AddMovieClusters') THEN
    ALTER TABLE movies ADD "ClusterCoordX" real;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912191746_AddMovieClusters') THEN
    ALTER TABLE movies ADD "ClusterCoordY" real;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912191746_AddMovieClusters') THEN
    ALTER TABLE movies ADD "ClusterCoordZ" real;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912191746_AddMovieClusters') THEN
    ALTER TABLE movies ADD "ClusterId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912191746_AddMovieClusters') THEN
    CREATE TABLE movie_clusters (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Label" character varying(200) NOT NULL,
        "Description" character varying(1000) NOT NULL,
        "MemberCount" integer NOT NULL,
        "Centroid" vector(384) NOT NULL,
        "CoordX" real NOT NULL,
        "CoordY" real NOT NULL,
        "CoordZ" real NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_movie_clusters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912191746_AddMovieClusters') THEN
    CREATE INDEX "IX_movies_ClusterId" ON movies ("ClusterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912191746_AddMovieClusters') THEN
    ALTER TABLE movies ADD CONSTRAINT "FK_movies_movie_clusters_ClusterId" FOREIGN KEY ("ClusterId") REFERENCES movie_clusters ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912191746_AddMovieClusters') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912191746_AddMovieClusters', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912193557_AddSearchLogs') THEN
    CREATE TABLE search_logs (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Query" character varying(500),
        "Mode" character varying(50) NOT NULL,
        "ResultCount" integer NOT NULL,
        "DurationMs" double precision NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_search_logs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912193557_AddSearchLogs') THEN
    CREATE INDEX "IX_search_logs_CreatedAt" ON search_logs ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912193557_AddSearchLogs') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912193557_AddSearchLogs', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912211315_AddCrawlJobQueryCriteria') THEN
    ALTER TABLE crawl_jobs ADD "Query" character varying(300);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912211315_AddCrawlJobQueryCriteria') THEN
    ALTER TABLE crawl_jobs ADD "QueryMode" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912211315_AddCrawlJobQueryCriteria') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912211315_AddCrawlJobQueryCriteria', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912232521_AddPersonProfileAndWikipediaUrl') THEN
    ALTER TABLE people ADD "ProfileUrl" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912232521_AddPersonProfileAndWikipediaUrl') THEN
    ALTER TABLE people ADD "WikipediaUrl" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912232521_AddPersonProfileAndWikipediaUrl') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912232521_AddPersonProfileAndWikipediaUrl', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912235132_AddPersonInfoUpdatedAt') THEN
    ALTER TABLE people ADD "InfoUpdatedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260912235132_AddPersonInfoUpdatedAt') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260912235132_AddPersonInfoUpdatedAt', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917142119_AddAppSettings') THEN
    CREATE TABLE app_settings (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "AnimationsEnabled" boolean NOT NULL,
        "CardHoverEffects" boolean NOT NULL,
        "CarouselEnabled" boolean NOT NULL,
        "CarouselSpeedSec" integer NOT NULL,
        "SphereDensity" character varying(20) NOT NULL,
        "HaloIntensity" character varying(20) NOT NULL,
        "ClusterPanelDefaultOpen" boolean NOT NULL,
        "NotificationsEnabled" boolean NOT NULL,
        "SpotifyAutoMatchEnabled" boolean NOT NULL,
        "DefaultPlayerVolume" integer NOT NULL,
        "PosterSphereZoom" character varying(20) NOT NULL,
        "PosterSpherePageSize" integer NOT NULL,
        CONSTRAINT "PK_app_settings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917142119_AddAppSettings') THEN
    INSERT INTO app_settings ("Id", "AnimationsEnabled", "CardHoverEffects", "CarouselEnabled", "CarouselSpeedSec", "ClusterPanelDefaultOpen", "DefaultPlayerVolume", "HaloIntensity", "NotificationsEnabled", "PosterSpherePageSize", "PosterSphereZoom", "SphereDensity", "SpotifyAutoMatchEnabled")
    VALUES (1, TRUE, TRUE, TRUE, 65, FALSE, 80, 'sottile', TRUE, 30, 'normale', 'leggera', TRUE);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917142119_AddAppSettings') THEN
    PERFORM setval(
        pg_get_serial_sequence('app_settings', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM app_settings) + 1,
            nextval(pg_get_serial_sequence('app_settings', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917142119_AddAppSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260917142119_AddAppSettings', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917144426_AddSettingsTheme') THEN
    ALTER TABLE app_settings ADD "Theme" character varying(20) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917144426_AddSettingsTheme') THEN
    UPDATE app_settings SET "Theme" = 'scuro'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260917144426_AddSettingsTheme') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260917144426_AddSettingsTheme', '10.0.12');
    END IF;
END $EF$;
COMMIT;

